---
 - name: lejob
   hosts: monGroupe
   tasks:
    - name: check nmon
      become: yes
      become_method: sudo
      apt:
       name: git
       state: latest


 - name: lejob2
   hosts: monGroupe
   tasks:
    - name: Créer fichier vide
      file:
              path: "/home/vagrant/COUCOU.txt"
              state: touch
              owner: root 

